export const GET_RECIPES = "GET_RECIPES";
export const GET_BULK_INFO = "GET_BULK_INFO";
export const GET_SAVED_RECIPES = "GET_SAVED_RECIPES";
export const GET_ALTERNATE_INGREDIENT = "GET_ALTERNATE_INGREDIENT";

export const SET_LOADING = "SET_LOADING";
export const SEARCH_ERROR = "SEARCH_ERROR";

export const UPDATE_INGREDIENT_LIST = "UPDATE_INGREDIENT_LIST";
