export const GET_RECIPES = "GET_RECIPES";
export const GET_BULK_INFO = "GET_BULK_INFO";

export const SET_LOADING = "SET_LOADING";
export const SEARCH_ERROR = "SEARCH_ERROR";

export const UPDATE_INGREDIENT_LIST = "UPDATE_INGREDIENT_LIST";
